#!/bin/sh
has() {
  command -v $1 >/dev/null
  return $?
}

packages_info() {
  {
    has qlist &> /dev/null && {
      qlist -IC | wc -l | tr -d "\n"; echo -n " (emerge) "
    } &
    has pacman-key &> /dev/null && {
      pacman -Q | wc -l | tr -d "\n"; echo -n " (pacman) "
    } &
    wait
  } > /run/user/$UID/hyperfetch/packages
}
