#!/usr/bin/env bash
count() {
    # Usage: count /path/to/dir/*
    #        count /path/to/dir/*/
    [ -e "$1" ] \
        && printf '%s\n' "$#" \
        || printf '%s\n' 0
}

function packages_info {
  module_output $(count /var/db/pkg/*/*) "packages"
}
