#!/bin/sh

# disable unicode
export LC_ALL=C
export LANG=C

module_output() {
  echo "${prefix_format}$1" > "/run/user/1000/hyperfetch/$2"
}


logo() {
  [ -e "distro/ascii-${ascii_distro}" ] && printf "${prefix_format}" && cat "distro/ascii-${ascii_distro}"
}

model_info() {
  module_output "${model_prefix}$(</sys/devices/virtual/dmi/id/product_name)" "model"
}

mem_fancy_info() {
  free_mem=$(awk '/MemAvailable/ { printf "%.0f \n", $2 }' /proc/meminfo)
  total_mem=$(awk '/MemTotal/ { printf "%.0f \n", $2 }' /proc/meminfo)
  mem_percent=$(( ($total_mem - $free_mem) / ($total_mem / 100) ))
  # from https://github.com/dylanaraps/pure-bash-bible
  ((elapsed=$mem_percent*15/100))
  printf -v prog "%${elapsed}s"
  printf -v total "%$((15-elapsed))s"
  module_output "(${prog// / ●}${total// / ○} )" "mem_fancy"
}

get_ascii_xy() {
  # ascii width is (width of ascii art + 2)
  case "$1" in 
    "arch") export ascii_width=34 ascii_height=15;;
    "gentoo") export ascii_width=37 ascii_height=17;;
    "bedrock") export ascii_width=40 ascii_height=17;;
    *) export ascii_width=0 ascii_height=0;;
  esac
}

title_info() {
  module_output "$USER\033[m@${prefix_format}${HOSTNAME:-$(hostname)}" "title"
}

term_info() {
  read parent_stat < /proc/$PPID/stat
  set -- $parent_stat
  terminal=$(cat /proc/$4/comm)
  module_output "${term_prefix}$terminal" "term"
}

cpu_info() {
  cpu=$(awk -F ":" '/model name/ {printf "%s\n", $2}' /proc/cpuinfo | head -n 1)
  module_output "${cpu_prefix}${cpu}" "cpu"
}

wm_info() {
  module_output "${wm_prefix}$(wmctrl -m | awk -F ":" '/Name: / {printf "%s\n", $2}')" "wm"
}

memory_info() {
  free_mem=$(awk '/MemAvailable/ { printf "%.0f \n", $2/1024 }' /proc/meminfo)
  total_mem=$(awk '/MemTotal/ { printf "%.0f \n", $2/1024 }' /proc/meminfo)
  module_output "${memory_prefix}$(( $total_mem - $free_mem ))M / ${total_mem}M" "memory"
}

shell_info() {
  module_output "${shell_prefix}$SHELL" "shell"
}

uptime_info() {
  read uptime < /proc/uptime
  old_ifs=$IFS
  IFS=.
  set -- $uptime
  uptime_first=$1
  IFS=$old_ifs
  hours=$((uptime_first / 3600))
  minutes=$((uptime_first % 3600 / 60))
  [ $hours = 0 ] || uptime_pretty="$hours hours"
  uptime_pretty="$uptime_pretty, $minutes minutes"
  module_output "${uptime_prefix} ${uptime_pretty}" "uptime"
}

kernel_info() {
  module_output "${kernel_prefix}$(uname -r)" "kernel"
}

distro_info() {
  module_output "${distro_prefix}$distro" "distro"
}

main() {
  mkdir -p /run/user/1000/hyperfetch/
  reset="\033[m"
  [ -e "/bedrock/etc/os-release" ] && . /bedrock/etc/os-release || . /etc/os-release
  export distro=$PRETTY_NAME distro_id=$ID
  # [ -e "distro/$distro_id" ] && . "distro/$distro_id" || . "distro/unknown"
  if [ -e "${HOME}/.config/hyperfetch/config" ];then
    . ${HOME}/.config/hyperfetch/config
  else
    infos="title distro kernel model memory uptime shell term wm cpu" 
    distro_prefix="Distro${reset}: "
    kernel_prefix="Kernel${reset}: "
    uptime_prefix="Uptime${reset}:"
    shell_prefix="Shell${reset}: "
    packages_prefix="Packages${reset}: "
    memory_prefix="Memory${reset}: "
    wm_prefix="WM${reset}:"
    cpu_prefix="CPU${reset}:"
    gpu_prefix="GPU${reset}: "
    term_prefix="Terminal${reset}: "
    mem_fancy_prefix="Memory${reset}: "
    model_prefix="Device${reset}: "
    prefix_format="\033[1;38;5;5m"
    ascii_show=1
    ascii_distro="${distro_id}"
  fi
  [ "$ascii_show" = "1" ] && {
    get_ascii_xy "$ascii_distro"
    logo "${ascii_distro}" &
  }
  {
    set -f
    set +f -- ${infos}
    for infos do 
      ${infos}_info &
    done
    wait
    printf "\033[${ascii_height}A"
    for infos do
      read info < /run/user/1000/hyperfetch/${infos}
      printf "\033[1000D\033[${ascii_width}C${info}\n"
    done
  }
  [ "$ascii_height" = 0 ] || printf "\033[$(( $ascii_height - 9 ))B"
}

main $@
